name: Deploy GitHub Pages

on:
  push:
    branches: ["main"] # Si attiva ogni volta che aggiungi un account dal pannello
  workflow_dispatch:   # Ti permette di farlo partire a mano se serve

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps: deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v5
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.' # Carica tutti i file del repository (compresi accountdata.txt e index.html)
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
